### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by Shard** [ant-design/kitchen#15]
I'm interested in being able to use this plugin but I can't find any documentation written in english.

**Comment by yasendimov** [comment]
+1

**Comment by chickdan** [comment]
+1

**Comment by asdkalluri** [comment]
+1

**Comment by bigomega** [comment]
At least the menu could be in English…
![image](https://user-images.githubusercontent.com/2320747/81699884-933c8680-9485-11ea-9671-a8de29484c31.png)
