### ISSUE TITLE
📌 Kitchen 2.19.0 发布日志

### ISSUE THREAD

**Issue by Esorakouki** [ant-design/kitchen#45]
`2020-05-29`  [⏬下载链接](https://gw.alipayobjects.com/os/kitchen/2055d980-cf13-4ebb-82c3-08c45b8d8221/kitchen-2.19.0.zip)

- 👋 正式移除了「自动排版」功能模块，请使用 Sketch 原生智能布局功能。
- 🐛 解决了框选多个图层时的卡顿问题。 [#386](https://www.yuque.com/kitchen/topics/386)

**Comment by afc163** [comment]
👍 性能大大提升
