### ISSUE TITLE
组件生成器只有表格，无法选择其他组件

### ISSUE THREAD

**Issue by stevejiachen** [ant-design/kitchen#6]
![image](https://user-images.githubusercontent.com/30266211/46450636-ac735080-c7d5-11e8-929e-08cdc8eaa596.png)

**Comment by afc163** [comment]
对的，只有表格，没有其他组件。

**Comment by stevejiachen** [comment]
宣传视频里有个下拉菜单选择不同组件，有计划增加其他组件吗？

**Comment by afc163** [comment]
视频已经更新了，可以看官网最新视频。antd 组件计划里不会再新增了，建议直接使用 Ant Design 提供的官方 symbol。

**Comment by stevejiachen** [comment]
好的谢谢
